blog/article/views.py
from typing import Dict
import requests
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from werkzeug.exceptions import NotFound
from sqlalchemy.orm import joinedload

from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static')


@article.route('/', methods=['GET'])
def article_list():
    articles: Article = Article.query.all()
    count_articles: Dict = requests.get('http://127.0.0.1:5000/api/articles/event_get_count/').json()  # RPC call
    return render_template(
        'articles/list.html',
        articles=articles,
        count_articles=count_articles['count'],
    )


@article.route('/<int:article_id>/', methods=['GET'])
def article_detail(article_id):
    _article: Article = Article.query.filter_by(
        id=article_id
    ).options(
        joinedload(Article.tags)
    ).one_or_none()

    if _article is None:
        raise NotFound
    return render_template(
        'articles/details.html',
        article=_article,
    )


# Вьюха до 7 урока:
# @article.route('/<int:article_id>/', methods=['GET'])
# def article_detail(article_id):
#     _article: Article = Article.query.filter_by(id=article_id).one_or_none()
#     if _article is None:
#         raise NotFound
#     return render_template(
#         'articles/details.html',
#         article=_article,
#     )


@article.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)


@article.route('/', methods=['POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)

    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data)

        if current_user.author:
            _article.author_id = current_user.author.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for('article.article_detail', article_id=_article.id))

    return render_template('articles/create.html', form=form)

blog/author/views.py
from flask import Blueprint, render_template

from blog.models import Author

author = Blueprint('author', __name__, url_prefix='/author', static_folder='../static')


@author.route('/')
def author_list():
    authors = Author.query.all()
    return render_template(
        'authors/list.html',
        authors=authors,
    )

blog/report/views.py
# Реализация blueprint - отчёты
from flask import Blueprint, render_template

report = Blueprint('report', __name__, url_prefix='/reports', static_folder='../static')  # report - name,
# __name__ - текущее название пакета, static_folder - где хранится статика


@report.route('/')  # регистрируем в роуте блюпринт по адресу localhost/report/ с функцией ниже:
def report_list():  # ф-ия, которая не принимает ничего
    return render_template(
        'reports/list.html',
        reports=[1, 2, 3, 4, 5]
    )

blog/user/views.py
# Реализация blueprint - пользователи
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user, login_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.app import login_manager
from blog.extensions import db
from blog.forms.users import UserRegisterForm
from blog.models import User

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')  # user - name,
# __name__ - текущее название пакета, static_folder - где хранится статика
# USERS = {
#     1: "James",
#     2: "Brian",
#     3: "Peter",
# }
# USERS = ['Alice', 'John', 'Mike']


@user.route('register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile', pk=current_user.id))

    form = UserRegisterForm(request.form)
    errors = []
    if request.method == 'POST' and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('Email error')
            return render_template('users/register.html', form=form)

        _user = User(
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)  # Авторизация после регистрации

    return render_template(
        'users/register.html',
        form=form,
        errors=errors,
    )


@user.route('/')  # регистрируем в роуте блюпринт по адресу localhost/user/ с функцией ниже:
def user_list():  # ф-ия, которая не принимает ничего
    from blog.models import User
    users = User.query.all()
    return render_template(  # Ф-ия render_template принимает в себя template name или list
        # (название нашего шаблона, который должен быть отрисован)
        'users/list.html',
        users=users,
    )


@user.route('/<int:pk>')  # pk - primary key
@login_required
def profile(pk: int):  # Принимает id юзера
    """Получение конкретного юзера"""
    from blog.models import User

    _user = User.query.filter_by(id=pk).one_or_none()  # Получаем конкретного юзера через фильтр по параметр, и
    # используем метод, который либо возвращает 1 элемент из выборки или none
    return render_template(
        'users/profile.html',
        user=_user,
    )

# Закоментил первую часть 3-го урока:
# @user.route('/<int:pk>')  # pk - primary key
# def get_user(pk: int):  # Принимает id юзера
#     """Получение конкретного юзера"""
#     from blog.models import User
#     _user = User.query.filter_by(id=pk).one_or_none()  # Получаем конкретного юзера через фильтр по параметр, и
#     # используем метод, который либо возвращает 1 элемент из выборки или none
#     return render_template(
#         'users/profile.html',
#         user=_user,
#     )


# Закомментировал первоначальный вариант работы с юзерами
# @user.route('/')  # регистрируем в роуте блюпринт по адресу localhost/user/ с функцией ниже:
# def user_list():  # ф-ия, которая не принимает ничего
#     return render_template(  # Ф-ия render_template принимает в себя template name или list
#         # (название нашего шаблона, который должен быть отрисован)
#         'users/list.html',
#         users=USERS,
#     )


# @user.route('/<int:pk>')  # pk - primary key
# def get_user(pk: int):  # Принимает id юзера
#     """Получение конкретного юзера"""
#     try:  # обрабатываем исключение, если юзера с таким id не будет
#         user_name = USERS[pk]
#     except KeyError:
#         raise NotFound(f'User id {pk} not found')  # Выдаём текст с отработанной ошибкой
#         # return redirect('/users/')  # В случае ошибки - редиректим на указанный адрес
#     user_pk = pk
#     return render_template(
#         'users/profile.html',
#         user_name=user_name,
#         user_pk=user_pk,
#     )

blog/templates/base.html
<!--базовый шаблон-->
<!doctype html>
<html lang="en">
  <head>
  <!-- required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
      <!-- Bootstrap CSS -->
      <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
      <!-- Загрузка CSS из Интернета -->
<!--      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"-->
<!--            rel="stylesheet"-->
<!--            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"-->
<!--            crossorigin="anonymous">-->
    {% endblock %}

    <title>
      {% block title %}
        My app -
      {% endblock %}
    </title>
  </head>
  <body>
    <div class="container">

      {% include 'navbar.html' %}


      <!-- Content here -->
      {% block body %}
        Hello base!
      {% endblock %}
    </div>

    {% block js %}
      <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
      <!-- Загрузка JS из Интернета -->
<!--      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"-->
<!--            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"-->
<!--            crossorigin="anonymous"></script>-->
    {% endblock %}
  </body>
</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('user.user_list') }}">Site by Flask</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.user_list') }}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('author.author_list') }}">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('report.report_list') }}">Reports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('article.article_list') }}">Articles</a>
        </li>
        {% if current_user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('article.create_article_form') }}">Create article</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout from {{ current_user.first_name }}</a>
          </li>
          {% if current_user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.index') }}">Admin panel</a>
          </li>
          {% endif %}
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
          </li>
        {% endif %}


      </ul>
    </div>
  </div>
</nav>